### PR TITLE
debloat

### PR DESCRIPTION
**Pull request by XyrenTheCoder**

### CODE REVIEW

**Comment by notsniped** [comment]
**Closing this pull request because the changes made here breaks compatibility for Pycord.**

Please note that we have/are currently switching from `discord.py` to `Pycord` library as Pycord works better with slash commands.

**Comment by XyrenTheCoder** [comment]
@notsniped i did nothing but debloared ur code ONLY, anything that u wrote was UNCHANGED so why dont u just update your code if u think pycord is better than discord.py which was being used in your code on github??

**Comment by XyrenTheCoder** [comment]
seems like its not my fault

**Comment by XyrenTheCoder** [comment]
> **Closing this pull request because the changes made here breaks compatibility for Pycord.**
> 
> Please note that we have/are currently switching from `discord.py` to `Pycord` library as Pycord works better with slash commands.

also, who knows?? u dont even update it then WHO KNOWS?

**Comment by notsniped** [comment]
> > **Closing this pull request because the changes made here breaks compatibility for Pycord.**
> 
> > 
> 
> > Please note that we have/are currently switching from `discord.py` to `Pycord` library as Pycord works better with slash commands.
> 
> 
> 
> also, who knows?? u dont even update it then WHO KNOWS?

image

**Comment by notsniped** [comment]
> @notsniped i did nothing but debloared ur code ONLY, anything that u wrote was UNCHANGED so why dont u just update your code if u think pycord is better than discord.py which was being used in your code on github??

I don't think that replacing `ApplicationContext` with a non-existent type is called debloating. And I don't think that replacing @slash.slash with @client.slash_command is called debloating either. 
If you look closely, `client` isn't defined, and `slash_command` won't work as we aren't importing `discord_slash`

**Comment by notsniped** [comment]
This is why this, and **only** this pull request is irrelevant here.

Also since I do not have immediate access to a pc, I will not be able to fix any of these changed files.

**Pull request closed without merging**
